/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package empmgmt.gui;

import empmgmt.dao.EmpDAO;
import empmgmt.dbutil.DBConnection;
import empmgmt.pojo.Employee;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class AddEmployeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployeeFrame
     */
    public AddEmployeeFrame() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addEmpPanel = new javax.swing.JPanel();
        lblAddNewEmp = new javax.swing.JLabel();
        lblEmpNo = new javax.swing.JLabel();
        lblEmpName = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        txtEmpNo = new javax.swing.JTextField();
        txtEmpName = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        btnAddEmp = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        addEmpPanel.setBackground(new java.awt.Color(102, 153, 255));

        lblAddNewEmp.setBackground(new java.awt.Color(0, 102, 102));
        lblAddNewEmp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAddNewEmp.setForeground(new java.awt.Color(102, 0, 102));
        lblAddNewEmp.setText("ADD NEW EMPLOYEE");

        lblEmpNo.setBackground(new java.awt.Color(102, 153, 255));
        lblEmpNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmpNo.setForeground(new java.awt.Color(153, 51, 0));
        lblEmpNo.setText("EmpNo");

        lblEmpName.setBackground(new java.awt.Color(102, 153, 255));
        lblEmpName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmpName.setForeground(new java.awt.Color(153, 51, 0));
        lblEmpName.setText("EmpName");

        lblSalary.setBackground(new java.awt.Color(102, 153, 255));
        lblSalary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSalary.setForeground(new java.awt.Color(153, 51, 0));
        lblSalary.setText("Salary");

        btnAddEmp.setBackground(new java.awt.Color(102, 51, 255));
        btnAddEmp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddEmp.setForeground(new java.awt.Color(102, 0, 102));
        btnAddEmp.setText("Add Emp");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 51, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 0, 102));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addEmpPanelLayout = new javax.swing.GroupLayout(addEmpPanel);
        addEmpPanel.setLayout(addEmpPanelLayout);
        addEmpPanelLayout.setHorizontalGroup(
            addEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmpPanelLayout.createSequentialGroup()
                .addGroup(addEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEmpPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblAddNewEmp))
                    .addGroup(addEmpPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(addEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpNo)
                            .addComponent(lblEmpName)
                            .addComponent(lblSalary))
                        .addGap(62, 62, 62)
                        .addGroup(addEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(addEmpPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnAddEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(60, 60, 60))
        );
        addEmpPanelLayout.setVerticalGroup(
            addEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddNewEmp)
                .addGap(47, 47, 47)
                .addGroup(addEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpNo)
                    .addComponent(txtEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(addEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpName)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(addEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalary)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(addEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEmp)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addEmpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addEmpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       OptionsFrame opFrame=new OptionsFrame();
       opFrame.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
     boolean result=validateInput();
     if(!result)
     {
     JOptionPane.showMessageDialog(null, "Please Fill All Input!!!", "Error!!!",JOptionPane.ERROR_MESSAGE);
     txtEmpNo.requestFocus();
     return;
     }
     try{
         int id=Integer.parseInt(txtEmpNo.getText());
         Employee emp=EmpDAO.findEmployeeById(id);
         if(emp!=null)
         {
         JOptionPane.showMessageDialog(null, "Employee with "+id+" ID Already exists","Information!!!",JOptionPane.INFORMATION_MESSAGE);
         return;
         }
     String empNo=txtEmpNo.getText();
     String empName=txtEmpName.getText();
     String empSal=txtSalary.getText();
     int eNo=Integer.parseInt(empNo);
     double eSal=Double.parseDouble(empSal);
     Employee e=new Employee();
     e.setEmpNo(eNo);
     e.setEmpName(empName);
     e.setSal(eSal);
     boolean response=EmpDAO.addEmployee(e);
     if(response){
     JOptionPane.showMessageDialog(null,"Record Inserted Successflully!!","Success!!!",JOptionPane.INFORMATION_MESSAGE);
     }
     else
         JOptionPane.showMessageDialog(null, "Could not insert record!!!","Error!!!",JOptionPane.ERROR_MESSAGE);
     }
     catch(NumberFormatException ex ){
     JOptionPane.showMessageDialog(null, "Please Enter digits only!!","Error!!!",JOptionPane.ERROR_MESSAGE);
     
     }
     catch(SQLException ex){
     JOptionPane.showMessageDialog(null,"Cannot connect to database!!!","DB Error!!",JOptionPane.ERROR_MESSAGE);
     ex.printStackTrace();
     }
    }//GEN-LAST:event_btnAddEmpActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
     DBConnection.closeConnection();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addEmpPanel;
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAddNewEmp;
    private javax.swing.JLabel lblEmpName;
    private javax.swing.JLabel lblEmpNo;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtEmpNo;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
     if(txtEmpNo.getText().isEmpty()||txtEmpName.getText().isEmpty()||txtSalary.getText().isEmpty())
         return false;
     return true;
    }
}
