/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package empmgmt.gui;

import empmgmt.dbutil.DBConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class OptionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptionsFrame
     */
    public OptionsFrame() {
        initComponents();
        btnDoTask.setMnemonic('d');
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup1 = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        optionPanel = new javax.swing.JPanel();
        lblSelectYourChoice = new javax.swing.JLabel();
        jrbAddEmployee = new javax.swing.JRadioButton();
        jrbSearchEmployee = new javax.swing.JRadioButton();
        jrbShowAllEmployee = new javax.swing.JRadioButton();
        jrbQuit = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        jrbUpdateEmployee = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        optionPanel.setBackground(new java.awt.Color(0, 102, 102));

        lblSelectYourChoice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSelectYourChoice.setForeground(new java.awt.Color(153, 204, 255));
        lblSelectYourChoice.setText("SELECT YOUR CHOICE");

        jrbAddEmployee.setBackground(new java.awt.Color(0, 102, 102));
        btnGroup1.add(jrbAddEmployee);
        jrbAddEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbAddEmployee.setForeground(new java.awt.Color(204, 153, 255));
        jrbAddEmployee.setText("Add Employee");
        jrbAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOptionFrameActionPerformed(evt);
            }
        });

        jrbSearchEmployee.setBackground(new java.awt.Color(0, 102, 102));
        btnGroup1.add(jrbSearchEmployee);
        jrbSearchEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbSearchEmployee.setForeground(new java.awt.Color(204, 153, 255));
        jrbSearchEmployee.setText("Search Employee");
        jrbSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOptionFrameActionPerformed(evt);
            }
        });

        jrbShowAllEmployee.setBackground(new java.awt.Color(0, 102, 102));
        btnGroup1.add(jrbShowAllEmployee);
        jrbShowAllEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbShowAllEmployee.setForeground(new java.awt.Color(204, 153, 255));
        jrbShowAllEmployee.setText("Show All Employees");
        jrbShowAllEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOptionFrameActionPerformed(evt);
            }
        });

        jrbQuit.setBackground(new java.awt.Color(0, 102, 102));
        btnGroup1.add(jrbQuit);
        jrbQuit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbQuit.setForeground(new java.awt.Color(204, 153, 255));
        jrbQuit.setText("Quit");
        jrbQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbOptionFrameActionPerformed(evt);
            }
        });

        btnDoTask.setBackground(new java.awt.Color(204, 255, 255));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(51, 51, 51));
        btnDoTask.setText("Do Task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        jrbUpdateEmployee.setBackground(new java.awt.Color(0, 102, 102));
        btnGroup1.add(jrbUpdateEmployee);
        jrbUpdateEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbUpdateEmployee.setForeground(new java.awt.Color(204, 153, 255));
        jrbUpdateEmployee.setText("Update/Delete Employee");

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jrbAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbSearchEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrbShowAllEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addComponent(jrbQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jrbUpdateEmployee))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionPanelLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(lblSelectYourChoice)
                .addGap(94, 94, 94))
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(btnDoTask)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSelectYourChoice)
                .addGap(34, 34, 34)
                .addComponent(jrbAddEmployee)
                .addGap(18, 18, 18)
                .addComponent(jrbSearchEmployee)
                .addGap(18, 18, 18)
                .addComponent(jrbShowAllEmployee)
                .addGap(18, 18, 18)
                .addComponent(jrbUpdateEmployee)
                .addGap(18, 18, 18)
                .addComponent(jrbQuit)
                .addGap(30, 30, 30)
                .addComponent(btnDoTask)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbOptionFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbOptionFrameActionPerformed

    }//GEN-LAST:event_jrbOptionFrameActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
      if(validateInput()==false){
         JOptionPane.showMessageDialog(null, "Select an operation first!!!", "Selection Error!!", JOptionPane.ERROR_MESSAGE);
         return;
       }
      else if(jrbAddEmployee.isSelected()==true){
      AddEmployeeFrame addEmp=new AddEmployeeFrame();
      addEmp.setVisible(true);
      this.dispose();
      }
      else if(jrbSearchEmployee.isSelected()==true){
      SearchEmployeeFrame searchEmp=new SearchEmployeeFrame();
      searchEmp.setVisible(true);
      this.dispose();
      }
      else if(jrbShowAllEmployee.isSelected()==true){
      ShowAllEmployee showEmp=new ShowAllEmployee();
      showEmp.setVisible(true);
      this.dispose();
      }
      else if(jrbUpdateEmployee.isSelected()==true){
      UpdateDeleteEmployeeFrame updateEmployee=new UpdateDeleteEmployeeFrame();
      updateEmployee.setVisible(true);
      this.dispose();
      }
      else{
      DBConnection.closeConnection();
      JOptionPane.showMessageDialog(null, "Thank You For Using App....", "Exit!!!", JOptionPane.INFORMATION_MESSAGE);
      System.exit(0);
      } 
    }//GEN-LAST:event_btnDoTaskActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    DBConnection.closeConnection();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.ButtonGroup btnGroup1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JRadioButton jrbAddEmployee;
    private javax.swing.JRadioButton jrbQuit;
    private javax.swing.JRadioButton jrbSearchEmployee;
    private javax.swing.JRadioButton jrbShowAllEmployee;
    private javax.swing.JRadioButton jrbUpdateEmployee;
    private javax.swing.JLabel lblSelectYourChoice;
    private javax.swing.JPanel optionPanel;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
     if(jrbAddEmployee.isSelected()==false&&jrbShowAllEmployee.isSelected()==false&&jrbSearchEmployee.isSelected()==false&&jrbQuit.isSelected()==false&&jrbUpdateEmployee.isSelected()==false)
     {
         return false;   
     }
     return true;
    }
}
