/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package empmgmt.gui;

import empmgmt.dao.EmpDAO;
import empmgmt.dbutil.DBConnection;
import empmgmt.pojo.Employee;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author abc
 */
public class ShowAllEmployee extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllEmployeeFrame
     */
    public ShowAllEmployee() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showAllEmployeePanel = new javax.swing.JPanel();
        lblViewAllEmp = new javax.swing.JLabel();
        btnShowAllRecords = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtShowAllEmp = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        showAllEmployeePanel.setBackground(new java.awt.Color(0, 102, 102));

        lblViewAllEmp.setBackground(new java.awt.Color(0, 102, 102));
        lblViewAllEmp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblViewAllEmp.setForeground(new java.awt.Color(204, 153, 0));
        lblViewAllEmp.setText("VIEW ALL EMPLOYEE DETAILS");

        btnShowAllRecords.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnShowAllRecords.setForeground(new java.awt.Color(153, 51, 0));
        btnShowAllRecords.setText("Show All Records");
        btnShowAllRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllRecordsActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(153, 51, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtShowAllEmp.setEditable(false);
        txtShowAllEmp.setColumns(20);
        txtShowAllEmp.setRows(5);
        jScrollPane2.setViewportView(txtShowAllEmp);

        javax.swing.GroupLayout showAllEmployeePanelLayout = new javax.swing.GroupLayout(showAllEmployeePanel);
        showAllEmployeePanel.setLayout(showAllEmployeePanelLayout);
        showAllEmployeePanelLayout.setHorizontalGroup(
            showAllEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showAllEmployeePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnShowAllRecords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showAllEmployeePanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(showAllEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showAllEmployeePanelLayout.createSequentialGroup()
                        .addComponent(lblViewAllEmp)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showAllEmployeePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        showAllEmployeePanelLayout.setVerticalGroup(
            showAllEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showAllEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblViewAllEmp)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(showAllEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowAllRecords)
                    .addComponent(btnBack))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(showAllEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(showAllEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    OptionsFrame opFrame=new OptionsFrame();
    opFrame.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnShowAllRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllRecordsActionPerformed
    ArrayList <Employee> empList=new ArrayList <>();
    try{
        empList=EmpDAO.getAllEmployees();
        StringBuilder sb=new StringBuilder();
        sb=sb.append("EMPNO\t"+"EMP NAME\t\t"+"EMP SALARY\n\n");
        for(Employee e:empList){
        sb=sb.append(e.getEmpNo()+"\t"+e.getEmpName()+"\t\t"+e.getSal()+"\n");
        }
        txtShowAllEmp.setText(sb.toString());
    }
    catch(SQLException ex){
    JOptionPane.showMessageDialog(null, "DB Error!!!");
    ex.printStackTrace();
    }
    }//GEN-LAST:event_btnShowAllRecordsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    DBConnection.closeConnection();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowAllEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowAllEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowAllEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowAllEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowAllEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnShowAllRecords;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblViewAllEmp;
    private javax.swing.JPanel showAllEmployeePanel;
    private javax.swing.JTextArea txtShowAllEmp;
    // End of variables declaration//GEN-END:variables
}
